/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author IsraelSantos
 */
public class Signos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signos.class.getName());

    /**
     * Creates new form Signos
     */
    public Signos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        areaAbas = new javax.swing.JTabbedPane();
        inicio = new javax.swing.JPanel();
        fundoInicio = new javax.swing.JLabel();
        aries = new javax.swing.JPanel();
        touro = new javax.swing.JPanel();
        gemeos = new javax.swing.JPanel();
        cancer = new javax.swing.JPanel();
        leao = new javax.swing.JPanel();
        virgem = new javax.swing.JPanel();
        libra = new javax.swing.JPanel();
        escorpiao = new javax.swing.JPanel();
        sagitario = new javax.swing.JPanel();
        capricornio = new javax.swing.JPanel();
        aquario = new javax.swing.JPanel();
        peixes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaAbas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        inicio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        fundoInicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\IsraelSantos\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\assets\\plano de fundo.jpg")); // NOI18N

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fundoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        areaAbas.addTab("Início", inicio);

        javax.swing.GroupLayout ariesLayout = new javax.swing.GroupLayout(aries);
        aries.setLayout(ariesLayout);
        ariesLayout.setHorizontalGroup(
            ariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        ariesLayout.setVerticalGroup(
            ariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Áries", aries);

        javax.swing.GroupLayout touroLayout = new javax.swing.GroupLayout(touro);
        touro.setLayout(touroLayout);
        touroLayout.setHorizontalGroup(
            touroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        touroLayout.setVerticalGroup(
            touroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Touro", touro);

        javax.swing.GroupLayout gemeosLayout = new javax.swing.GroupLayout(gemeos);
        gemeos.setLayout(gemeosLayout);
        gemeosLayout.setHorizontalGroup(
            gemeosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        gemeosLayout.setVerticalGroup(
            gemeosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Gêmeos", gemeos);

        javax.swing.GroupLayout cancerLayout = new javax.swing.GroupLayout(cancer);
        cancer.setLayout(cancerLayout);
        cancerLayout.setHorizontalGroup(
            cancerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        cancerLayout.setVerticalGroup(
            cancerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Câncer", cancer);

        javax.swing.GroupLayout leaoLayout = new javax.swing.GroupLayout(leao);
        leao.setLayout(leaoLayout);
        leaoLayout.setHorizontalGroup(
            leaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        leaoLayout.setVerticalGroup(
            leaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Leão", leao);

        javax.swing.GroupLayout virgemLayout = new javax.swing.GroupLayout(virgem);
        virgem.setLayout(virgemLayout);
        virgemLayout.setHorizontalGroup(
            virgemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        virgemLayout.setVerticalGroup(
            virgemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Virgem", virgem);

        javax.swing.GroupLayout libraLayout = new javax.swing.GroupLayout(libra);
        libra.setLayout(libraLayout);
        libraLayout.setHorizontalGroup(
            libraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        libraLayout.setVerticalGroup(
            libraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Libra", libra);

        javax.swing.GroupLayout escorpiaoLayout = new javax.swing.GroupLayout(escorpiao);
        escorpiao.setLayout(escorpiaoLayout);
        escorpiaoLayout.setHorizontalGroup(
            escorpiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        escorpiaoLayout.setVerticalGroup(
            escorpiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Escorpião", escorpiao);

        javax.swing.GroupLayout sagitarioLayout = new javax.swing.GroupLayout(sagitario);
        sagitario.setLayout(sagitarioLayout);
        sagitarioLayout.setHorizontalGroup(
            sagitarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        sagitarioLayout.setVerticalGroup(
            sagitarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Sagitário", sagitario);

        javax.swing.GroupLayout capricornioLayout = new javax.swing.GroupLayout(capricornio);
        capricornio.setLayout(capricornioLayout);
        capricornioLayout.setHorizontalGroup(
            capricornioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        capricornioLayout.setVerticalGroup(
            capricornioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Capricórnio", capricornio);

        javax.swing.GroupLayout aquarioLayout = new javax.swing.GroupLayout(aquario);
        aquario.setLayout(aquarioLayout);
        aquarioLayout.setHorizontalGroup(
            aquarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        aquarioLayout.setVerticalGroup(
            aquarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Aquário", aquario);

        javax.swing.GroupLayout peixesLayout = new javax.swing.GroupLayout(peixes);
        peixes.setLayout(peixesLayout);
        peixesLayout.setHorizontalGroup(
            peixesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3006, Short.MAX_VALUE)
        );
        peixesLayout.setVerticalGroup(
            peixesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );

        areaAbas.addTab("Peixes", peixes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaAbas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaAbas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aquario;
    private javax.swing.JTabbedPane areaAbas;
    private javax.swing.JPanel aries;
    private javax.swing.JPanel cancer;
    private javax.swing.JPanel capricornio;
    private javax.swing.JPanel escorpiao;
    private javax.swing.JLabel fundoInicio;
    private javax.swing.JPanel gemeos;
    private javax.swing.JPanel inicio;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel leao;
    private javax.swing.JPanel libra;
    private javax.swing.JPanel peixes;
    private javax.swing.JPanel sagitario;
    private javax.swing.JPanel touro;
    private javax.swing.JPanel virgem;
    // End of variables declaration//GEN-END:variables
}
